#!/usr/bin/env bash
# update package repositories
apt-get -y update

# install nginx if not already installed
apt-get -y install nginx

# ensure uncomplicatd firewall allows traffic on port 80
ufw allow 'Nginx HTTP'

# echo content to index.html
echo 'Hello World!' > /var/www/html/index.html

# restart engine x
service nginx start
