#!/usr/bin/env bash
# Update package lists

apt-get update

# Install engine x
apt-get install -y nginx

# Configure engine x to listen to port 80
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    location / {
        echo 'Hello World!';
    }
}" > /etc/nginx/sites-available/default

# Restart engine x server
service nginx restart
