#!/usr/bin/env bash
# Update package lists

apt-get update

# Install engine x
apt-get install -y nginx

# Configure engine x to listen to port 80
echo 'Hello World!' >> /var/www/html/index.html
# Restart engine x server
service nginx start
