#!/bin/bash
# Install Nginx if not already installed
sudo apt-get update
sudo apt-get -y install nginx

# Create a new Nginx configuration file for redirection
sudo tee /etc/nginx/sites-available/redirect <<EOF
server {
    listen 80;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        return 404;
    }
}
EOF

# Create a symbolic link to enable the redirection configuration
sudo ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/

# Remove the default Nginx configuration
sudo rm /etc/nginx/sites-enabled/default

# Restart Nginx to apply the changes
sudo service nginx restart
