#!/usr/bin/env bash
# Configure Nginx server on ubnuntu web-01 and local one
# Update package repositories
apt-get -y update

# Install engine x if not exists
apt-get -y install nginx

# Firewall rules to allow engine x
ufw allow 'Nginx HTTP'

echo "Hello World" | sudo tee /var/www/html/index
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://fmovies.to/tv/superman-lois-178zv/1-1 permanent;' /etc/nginx/sites-available/default

# Restart engine x server
service nginx restart
