#!/usr/bin/env bash

# Update package repositories
apt-get update

# Install nginx if not already installed
apt-get -y install nginx

# Configure firewall to allow requests through port 80
sudo ufw allow 'Nginx HTTP'

# Create directory for web content
mkdir -p /var/www/html && chmod -R 777 /var/www

# Change permissions to allow easy file creation in the directory
# chmod -R 755 /var/www

# Create the index page
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Create a webpage for error 404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure custom header and redirect for a single page (/redirect_me)
sudo sed -i 's/# server_tokens off;/server_tokens off;\n\tadd_header X-Served-By $hostname;\n\trewrite ^\/redirect_me https://fmovies.to/tv/superman-lois-178zv/1-7 permanent;/g' /etc/nginx/sites-available/default

# Configure redirect for 404 error page
sudo sed -i 's/# error_page 404/    error_page 404/g' /etc/nginx/sites-available/default
sudo sed -i 's/#     location = \/404.html {/    location = \/404.html {/g' /etc/nginx/sites-available/default
sudo sed -i 's/#         root \/usr\/share\/nginx\/html;/        root \/var\/www\/html;/g' /etc/nginx/sites-available/default
sudo sed -i 's/#         internal;/        internal;/g' /etc/nginx/sites-available/default

# Restart the web server after updating the settings
service nginx restart
