#!/usr/bin/env bash
# Update package repositories
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Create directory structure and default files
sudo mkdir -p /var/www/html
sudo cat > /var/www/html/index.html <<EOF
<!DOCTYPE html>
<html>
<head>
    <title>Hello World</title>
</head>
<body>
    <h1>Hello World</h1>
</body>
</html>
EOF

sudo cat > /var/www/html/404.html <<EOF
<!DOCTYPE html>
<html>
<head>
    <title>404 Not Found</title>
</head>
<body>
    <h1>404 Not Found</h1>
    <p>Ceci n'est pas une page.</p>
</body>
</html>
EOF

# Configure engine x server
sudo cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By \$hostname;
    root /var/www/html;
    index index.html index.htm;

    location /redirect_me {
        return 301 http://cuberule.com/;
    }

    error_page 404 /404.html;
    location /404 {
        internal;
    }
}
EOF

# Restart Nginx
sudo service nginx restart

sudo ufw allow 'Nginx HTTP'
