#!/usr/bin/env bash
# Enable IP Fowarding
sudo sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/' /etc/sysctl.conf
sudo sysctl -p

# Configure port fowarding in ufw
sudo iptables -t nat -A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80
sudo iptables-save | sudo tee /etc/iptables/rules.v4

# Apply the changes
sudo sysctl -p
# Restart the firewall
sudo service ufw restart
