#!/usr/bin/env bash
# Set Container ID and PORT
CONTAINER_ID="5c5764d2f60d"

# Start the container
docker start $CONTAINER_ID

# Execute a command in the running container to start Apache
docker exec -d $CONTAINER_ID service apache2 start
