#!/usr/bin/env bash
# Update package repositories
sudo apt-get update

# Install nginx if not installed
sudo apt-get install -y nginx

# Create a backup file for the default nginx configuration
sudo cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak

# Modify the Nginx configuration file to run as the 'nginx'
# user and listen on all IPs on port 8080
sed -i 's/user\s\+nginx;/user nginx;\nworker_processes auto;/g' /etc/nginx/nginx.conf

echo -e "    listen 8080 default_server;\n    listen [::]:8080 default_server;" >> /etc/nginx/nginx.conf

# Remove the default site configuration to avoid conflicts
rm -f /etc/nginx/sites-available/default
rm -f /etc/nginx/sites-enabled/default

# Restart engine x to apply the changes
sudo service nginx restart
